### ISSUE TITLE
How to create our own model with CT images and ground truth

### ISSUE THREAD

**Issue by jayanth-culli** [IBBM/Cascaded-FCN#10]
Hi,
I have abdominal CT scan data sets for 15 patients. Among them 5 data sets are with HCC legions. I also have the ground truths of liver for all the data sets and also ground truth of legions for the 5 data sets with HCC.
Can you help me train this data to create my own caffe model?

Thanks,
Jayanth.

**Comment by mohamed-ezz** [comment]
Hi Jayanth,

What kind of help do you need ?
You can find the training notebook and prototxts here : https://github.com/mohamed-ezz/saratan/tree/master/notebooks
