### ISSUE TITLE
Finetune Ultrasound 2D Dataset.

### ISSUE THREAD

**Issue by mateovillaarias** [IBBM/Cascaded-FCN#11]
Hi,

I would like to train my dataset , which consist of ultrasound 2D images, in gray-scale, for making automatic bone segmentation . I have no GPU, so I would like to finetune your model in order to do the training faster .  My images are of different sizes( the height is fixed at 512, but the width varies between 300 and 512. Is there any special consideration in this case ? Your cand find attached an example of an image  and the ground truth 
![image_01_0541_croped](https://cloud.githubusercontent.com/assets/23532299/24546110/208cd664-160a-11e7-834b-2d24bfad2aec.png)
![image_01_0541_croped](https://cloud.githubusercontent.com/assets/23532299/24546123/267275f2-160a-11e7-910c-27067059bd57.jpg)

Thank you very much,

Cordially,

Mateo Villa

**Comment by mohamed-ezz** [comment]
Hi @mateovilla2, 
Regarding the different image size, I think it's fine, but make sure to change cropping parameters accordingly in the training/testing prototxt.

Without a GPU I think training will be way too slow for this large model. If there's no chance to access a GPU, I would try a smaller model. But try it out and see how much time you can afford to wait until training converges.

**Comment by sqbqamar** [comment]
Hi,
Can i get training prototxt of your work..
