### ISSUE TITLE
paper question

### ISSUE THREAD

**Issue by manutdzou** [IBBM/Cascaded-FCN#12]
Hi, I have read your paper many times and I have some questions. Hope you can help me, thank you!
in Table 1, are all the results for liver segmentation? If the results are for liver, in my option the first branch of Cascaded UNET is for liver segmentation and it is just a UNET, why the result is very different from the UNET?(DICE 93.1% vs 72.9%).

**Comment by mohamed-ezz** [comment]
Hi @manutdzou ,

Thanks for your question. By UNET we mean the model where we tried to segment both the liver and the lesion (and background..so 3 class problem), and in this table we report the Liver dice (72.9%)

In the other row (Cascaded UNET) we have a model that segments just the liver (referred to as Step1 UNET and it's a 2 class problem) for which the dice is 93.1% (and we haven't reported the lesion dice for Step2 of the cascade).
