### ISSUE TITLE
Issue with imshow in cascaded_unet_inference.ipynb

### ISSUE THREAD

**Issue by scotwilli** [IBBM/Cascaded-FCN#14]
RuntimeError: Could not create write struct with imshow

which library to use for imshow - opencv or matplotlib?

**Comment by mohamed-ezz** [comment]
There's a helper function named `imshow` in the notebook. Internally it uses `plt.imshow()` (from matplotlib)

**Comment by scotwilli** [comment]
I added the line import matplotlib.pyplot as plt
import dicom
import natsort
import glob, os
import re
import matplotlib.pyplot as plt

But still Iam getting the same issue. I uninstalled and re-installed matplotlib. But still couldnt get away with the issue. 
![cascade-net-error](https://cloud.githubusercontent.com/assets/11065947/25946332/3d7d3420-3668-11e7-9a48-a2c78d76989e.png)

**Comment by mohamed-ezz** [comment]
You seem to be invoking a wrong `imshow`. Please check `imshow?`.

You should be using the `imshow` defined above, in the notebook
