### ISSUE TITLE
The dropbox link of weights.caffemodel were expired

### ISSUE THREAD

**Issue by RenieWell** [IBBM/Cascaded-FCN#15]
The dropbox link of the two weights.caffemodel were expired, the dropbpx told me the file was not exist or has been moved.

**Comment by mohamed-ezz** [comment]
The links were upgraded weeks ago.

**Comment by RenieWell** [comment]
The new links https://dl.dropboxusercontent.com/u/28351742/CascadedFCN/step1_weights.caffemodel
and https://dl.dropboxusercontent.com/u/28351742/CascadedFCN/step1_weights.caffemodel
still not work 
I have tried everything I can. Could you please check the links? @mohamed-ezz

**Comment by mohamed-ezz** [comment]
Hello @RenieWell, the links were updated in the README.md, but not in the notebook yet.

See https://github.com/IBBM/Cascaded-FCN/blob/master/models/cascadedfcn/step1/README.md
and https://github.com/IBBM/Cascaded-FCN/blob/master/models/cascadedfcn/step2/README.md

It would help if you can replace dead links in the notebook with the links above and create a pull request.

Thank you.

**Comment by mohamed-ezz** [comment]
I have updated the links in the notebook too. Thanks for pointing that out.

**Comment by RenieWell** [comment]
Thank you for your help!

**Comment by manutdzou** [comment]
do you reproduce the result?
@RenieWell
