### ISSUE TITLE
#question. Do we need to train for step 2 in cascaded FCN?

### ISSUE THREAD

**Issue by dk67604** [IBBM/Cascaded-FCN#21]
Hello,

I'm following this notebook: https://github.com/mohamed-ezz/saratan/tree/master/notebooks for Step 1 caffemodel, I just need clarification on my understanding once I trained for dataset 3D-Ircadb using this notebook so basically my model is ready to segment liver. How about for lesion, do I need to save the result after segmenting in Step1 and use the same notebook for creating the Step 2 model.
Please help me to understand, I don't see how's this is taken care in the code.

**Comment by mohamed-ezz** [comment]
You are right, this notebook you're referring to is used to train both.
