### ISSUE TITLE
Pretrained TensorFlow Models

### ISSUE THREAD

**Issue by zakizhou** [IBBM/Cascaded-FCN#25]
Can you provide the pre-trained tensorflow model(including graph and ckpt) for us? Training from scratch really takes a lot of time and need gpus with big memory. Thank you very much!

**Comment by alizeshana** [comment]
Do let me know if you get it.

**Comment by zakizhou** [comment]
@alizeshana I forked that tensorflow-implementation branch and successfully started the training but then I got memory error because I only have one gtx 1060 6G card. If you have more powerful gpus maybe you can train it yourself

**Comment by alizeshana** [comment]
@zakizhou I am  facing the same issue on my gtx 740M 2GB. :p

Do let me know if you find the trained model.

**Comment by mohamed-ezz** [comment]
I think it's not very hard to convert the .caffeweights provided in this repo to a Keras .hdf5.

This is roughly how I would do it : 

1. Define the same network in Keras (this may be the most time consuming). Make sure there are no implementation differences for any of the layers between Caffe and Keras.
2. A script Loads the .caffeweights and prototxt using caffe python library
3. Compile the keras architecture
4. Use keras's `model.layers[i].set_weights(caffeweights)`, while figuring out any reshaping needed. Do this for every layer.
5. Save Keras's model as .hdf5 `model.save_weights(...)`

**Comment by mohamed-ezz** [comment]
If you manage to do this, I would appreciate sharing your work with others by submitting a PR with the Tensorflow/Keras weights.
