### ISSUE TITLE
Result is very worse followed by the ipynb file

### ISSUE THREAD

**Issue by UpCoder** [IBBM/Cascaded-FCN#26]
Hi, I execute the cascaded_unet_inference.ipynb that doesn't report any questions, but the result is worse.
The result of step1 is shown as follow:
![image](http://ocnsbpp0d.bkt.clouddn.com/Screenshot%20from%202017-12-20%2017-43-16.png)

Any one know the reason?
Thank you very much

**Comment by fuentesdt** [comment]
@UpCoder i'm getting the same thing on ubuntu 16.04 with cpu only version. are you able to run it from the docker? with gpu?

**Comment by UpCoder** [comment]
No, I still not solve the problem. Then I train the model from scratch with tensorflow version. The segmentation of liver is acceptable, but the lesions's can be acceptable. 
I don't run it from the docker, I directly use the GPU server.

**Comment by fuentesdt** [comment]
thanks @mohamed-ezz 

seems that you need to use the same caffe version from the docker:


root@maeda:/opt/caffe# cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/mohamed-ezz/caffe.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "jonlong"]
        remote = origin
        merge = refs/heads/jonlong
root@maeda:/opt/caffe# git log
commit 876e387a6d7f8974f68f42beacd3728b4fc92ff7
Author: Mohamed Ezz <moh.ezz8@gmail.com>
Date:   Thu Feb 18 01:24:04 2016 +0100

    Add class weighting feature for softmax_loss layer

$ git clone https://github.com/mohamed-ezz/caffe.git caffe/docker
$ cd caffe/docker;  git branch docker 876e387a6d7f8974f68f42beacd3728b4fc92ff7 ; git checkout docker

![screen shot 2018-01-03 at 8 42 01 pm](https://user-images.githubusercontent.com/906479/34548294-e5e9e338-f0c6-11e7-8420-f1844a514e56.png)
