### ISSUE TITLE
Incorrect output after step 1.

### ISSUE THREAD

**Issue by XiaonanZang** [IBBM/Cascaded-FCN#5]
Hi, I have run the notebook and seemed to obtain an incorrect prediction after step1.

For comparison, I have used the same example from https://github.com/cjayanth95/liverseg/blob/master/custom_outs_updated.ipynb.

This is my output: https://github.com/XiaonanZang/liverseg/blob/master/cascaded_unet_inference-Copy1.ipynb.

I have followed your instruction and built the caffe from the provided git.

Could you help me on this issue?

Thank you very much.

Xiaonan Zang

**Comment by XiaonanZang** [comment]
Hi,

After further reviewed the issue regarding the offset. I found that even with the caffe at: https://github.com/mohamed-ezz/caffe/tree/jonlong, I still have to specifically set up the offsets.

I set the offsets based on the answer you provided at: https://groups.google.com/forum/#!topic/caffe-users/YSRYy7Nd9J8

And now my output perfectly matched the output from: https://github.com/cjayanth95/liverseg/blob/master/custom_outs_updated.ipynb.

Thanks,
Xiaonan

**Comment by dk67604** [comment]
How did you set up the crop offset for caffe?
