### ISSUE TITLE
Discrepancy in dice scores

### ISSUE THREAD

**Issue by kiranvaidhya** [IBBM/Cascaded-FCN#7]
You have reported a dice score of **82.3%** for the lesions in the [first paper](https://arxiv.org/pdf/1610.02177.pdf). It's not clear as to what this metric belongs to. Is it the dice score for lesion at training or testing?

In the [follow-up paper](https://arxiv.org/pdf/1702.05970.pdf), it's been reported as follows: _"In general, we observe significant additional improvements for Dice overlaps of liver segmentations, from mean Dice 93.1% to 94.3% after applying the 3D CRF. For lesions we could achieve a Dice score of_ **56%** _at a standard deviation of 26% with a 2 fold cross-validation."_

Can you clarify me regarding the correct results? Why is there a discrepancy?

**Comment by PatrickChrist** [comment]
Thanks for asking.
The dice score of 82.3% in the first paper is referring to figure 1. The dice score of the final slice is 82% dice. In the follow-up paper we report mean dice over volumes with a 2 fold cross validation.
