### ISSUE TITLE
model link is not found

### ISSUE THREAD

**Issue by manutdzou** [IBBM/Cascaded-FCN#9]
Hi, I found your model link is disable, can you update your link or give me a web link, thank you

**Comment by Chandanpanda** [comment]
Me too!

**Comment by mohamed-ezz** [comment]
Dropbox invalidated public links. I'll update the links in the next couple of days and let you know, thanks for the report

**Comment by Chandanpanda** [comment]
Thanks a lot!

**Comment by shivin101** [comment]
any updates

**Comment by mohamed-ezz** [comment]
Link updated.
I was trying to get the files to a proper storage location, but since this may take sometime I republished new dropbox links.

**Comment by Chandanpanda** [comment]
thanks!

**Comment by manutdzou** [comment]
thanks it works


发自网易邮箱大师
On 03/28/2017 00:04, Mohamed Ezz wrote:

Link updated.
I was trying to get the files to a proper storage location, but since this may take sometime I republished new dropbox links.
